version: '3'

services:
  frontend:
    container_name: 'swe-frontend'
    labels:
      io.portainer.accesscontrol.teams: SWE
    build:
      dockerfile: ./Dockerfile
    networks:
      ipvlan:
        ipv4_address: 192.168.25.100
    restart: always

networks:
  ipvlan:
    external: true
